import type { RuleDefinition, Ruleset } from "../domain/types.js";
import { parseRuleset } from "./schema.js";

const source = {
  regulation: {
    sourceId: "ALG-REG",
    url: "https://allegro.pl/regulamin",
    title: "Regulamin Allegro",
  },
  titleDescription: {
    sourceId: "ALG-TITLE-DESC",
    url: "https://help.allegro.com/pl/sell/c/zasady-dla-tytulu-i-opisu",
    title: "Zasady dla tytułu i opisu",
  },
  catalog: {
    sourceId: "ALG-CATALOG",
    url: "https://help.allegro.com/pl/sell/c/dodawanie-produktow-do-katalogu",
    title: "Dodawanie produktów do Katalogu",
  },
  listing: {
    sourceId: "ALG-LISTING",
    url: "https://help.allegro.com/pl/sell/c/jak-wystawiac-oferty",
    title: "Jak wystawiać oferty",
  },
  intellectualProperty: {
    sourceId: "ALG-IP",
    url: "https://help.allegro.com/pl/sell/c/prawa-autorskie-i-wlasnosci-intelektualnej",
    title: "Prawa autorskie i własność intelektualna",
  },
} as const;

function defineRule(rule: RuleDefinition): RuleDefinition {
  return rule;
}

export const allegroPlRuleset: Ruleset = parseRuleset({
  rulesetId: "allegro-pl-2026-08-20.1",
  marketplace: "allegro-pl",
  retrievedAt: "2026-08-20T00:00:00+02:00",
  sources: Object.values(source),
  rules: [
    defineRule({
      ruleId: "ALG-TITLE-001",
      field: "offer.title",
      severity: "error",
      kind: "length",
      assertion: { minCharacters: 12, maxCharacters: 75 },
      messagePl: "Tytuł powinien mieć od 12 do 75 znaków ze spacjami.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-TITLE-002",
      field: "offer.title",
      severity: "error",
      kind: "word_count",
      assertion: { minWords: 3 },
      messagePl: "Tytuł powinien zawierać co najmniej 3 słowa.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-TITLE-003",
      field: "offer.title",
      severity: "error",
      kind: "forbidden_phrases",
      assertion: {
        phrases: ["tanio", "najtaniej", "okazja", "nowość", "promocja", "hit", "zobacz to"],
      },
      messagePl: "Tytuł nie może zawierać fraz promocyjnych ani reklamowych.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-TITLE-004",
      field: "offer.title",
      severity: "error",
      kind: "semantic_relevance",
      assertion: { onlyListedProduct: true },
      messagePl: "Tytuł może dotyczyć wyłącznie sprzedawanego produktu i wariantu.",
      sourceId: source.titleDescription.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-TITLE-005",
      field: "offer.title",
      severity: "error",
      kind: "keyword_repetition",
      assertion: { maxMeaningfulTokenOccurrences: 3 },
      messagePl: "Nie powtarzaj wielokrotnie tych samych słów kluczowych.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-DESC-001",
      field: "offer.description",
      severity: "error",
      kind: "completeness",
      assertion: { minCharacters: 80 },
      messagePl: "Opis powinien być kompletny i nie może urywać się w połowie.",
      sourceId: source.titleDescription.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-DESC-002",
      field: "offer.description",
      severity: "error",
      kind: "language",
      assertion: { language: "pl" },
      messagePl: "Opis na allegro.pl powinien być po polsku i nie mieszać języków.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-DESC-003",
      field: "offer.description",
      severity: "warning",
      kind: "language_quality",
      assertion: {},
      messagePl: "Opis nie powinien zawierać błędów językowych, literówek ani przypadkowych fraz.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-DESC-004",
      field: "offer.description",
      severity: "blocker",
      kind: "semantic_relevance",
      assertion: { onlyListedProduct: true },
      messagePl: "Opis może dotyczyć wyłącznie produktu sprzedawanego w tej ofercie.",
      sourceId: source.titleDescription.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-DESC-005",
      field: "offer.description",
      severity: "blocker",
      kind: "cross_field_consistency",
      assertion: { fields: ["offer.title", "offer.parameters", "offer.images"] },
      messagePl: "Opis musi być zgodny z tytułem, parametrami i zdjęciami.",
      sourceId: source.titleDescription.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-DESC-006",
      field: "offer.description",
      severity: "error",
      kind: "variant_isolation",
      assertion: {},
      messagePl: "Opis nie może przedstawiać innych wariantów produktu jako elementu tej oferty.",
      sourceId: source.titleDescription.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-DESC-007",
      field: "offer.description",
      severity: "error",
      kind: "forbidden_phrases",
      assertion: { phrases: ["gratis", "tanio", "promocja", "hit", "prezent"] },
      messagePl: "Opis nie może zawierać fraz reklamowych i marketingowych.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-DESC-008",
      field: "offer.description",
      severity: "error",
      kind: "keyword_repetition",
      assertion: { maxMeaningfulTokenOccurrences: 8 },
      messagePl: "Nie używaj słów kluczowych w sposób manipulujący wyszukiwaniem.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-DESC-009",
      field: "offer.description",
      severity: "blocker",
      kind: "personal_and_payment_data",
      assertion: {},
      messagePl: "Opis nie może zawierać telefonu, e-maila ani danych do płatności.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-DESC-010",
      field: "offer.description",
      severity: "error",
      kind: "misplaced_information",
      assertion: {
        phrases: ["urlop", "przerwa w sprzedaży", "gwarancja", "termin przydatności", "personalizacja"],
      },
      messagePl: "Nie umieszczaj w opisie danych przeznaczonych do innych sekcji Allegro.",
      sourceId: source.titleDescription.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-DESC-011",
      field: "offer.description",
      severity: "error",
      kind: "source_origin",
      assertion: { phrases: ["od dystrybutora", "z hurtowni", "bezpośrednio od producenta"] },
      messagePl: "Opis nie powinien zawierać informacji o miejscu pozyskania produktu.",
      sourceId: source.titleDescription.sourceId,
      autofix: true,
    }),
    defineRule({
      ruleId: "ALG-DESC-012",
      field: "offer.description",
      severity: "blocker",
      kind: "copyright_review",
      assertion: {},
      messagePl: "Nie kopiuj opisów konkurencyjnych ofert; używaj wyłącznie treści, do których masz prawa.",
      sourceId: source.intellectualProperty.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-PARAM-001",
      field: "offer.parameters.gtin",
      severity: "blocker",
      kind: "gtin",
      assertion: { requiredWhenApplicable: true },
      messagePl: "GTIN/EAN musi być poprawny i zgodny z produktem w Katalogu Allegro.",
      sourceId: source.listing.sourceId,
      autofix: false,
    }),
    defineRule({
      ruleId: "ALG-PARAM-002",
      field: "offer.parameters",
      severity: "error",
      kind: "identity_completeness",
      assertion: { fields: ["brand", "manufacturerCode", "model", "gtin"] },
      messagePl: "Uzupełnij markę, kod producenta, model i GTIN, jeśli dotyczą produktu.",
      sourceId: source.catalog.sourceId,
      autofix: false,
    }),
  ],
});

